backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)

media_folder: static/uploads/images
public_folder: uploads/images

display_url: https://practical-kirch-724ea6.netlify.com

collections:
  - name: "pages"
    label: "Pages"
    editor:
      preview: false
    files:
      - label: "Landing Page"
        name: "landing"
        file: "content/landing-page.md"
        fields:
          - { label: Title, name: title, widget: hidden, default: Landing Page }
          - { label: "Featured Image", name: "fimage", widget: hidden, default: "./images/opengraph.jpg" }
          - label: "Sections"
            name: "sections"
            widget: "list"
            types:
              - label: "About"
                name: "about"
                widget: object
                fields:
                  - { label: "Title", name: "title", widget: "string" }
                  - {
                      label: "Featured Image",
                      name: "image",
                      widget: "image",
                      default: "roto.jpg",
                    }
                  - {
                      label: "Description",
                      name: "description",
                      widget: "markdown",
                    }
              - label: "Paragraph"
                name: "paragraph"
                widget: object
                fields:
                  - { label: "Title", name: "title", widget: "string" }
                  - { label: "Paragraph", name: "paragraph", widget: "string" }
  - name: "settings"
    label: "Settings"
    editor:
      preview: false
    files:
      - name: "settings"
        label: "Settings"
        file: "content/settings.md"
        fields:
          - { label: Title, name: title, widget: hidden, default: Settings }
          - label: "Social Media"
            name: "social-media"
            widget: "list"
            allow_add: false
            fields:
              - { label: "URL", name: url, widget: string, required: false }
              - { label: "Type", name: type, widget: hidden, default: "fb"}
              - { label: "Icon", name: icon, widget: hidden, default: "<i class=\"fab fa-facebook-square\"></i>" }
          - label: "Contact Information"
            name: contact-info
            widget: "object"
            fields: 
              - { label: "Address", name: address, widget: string}
              - { label: "Phone Number", name: phone, widget: string}
              - { label: "Email Address", name: email, widget: string}
